version: "3"


services:
  flask_app:
    container_name: flask_app
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      PYTHONPATH: /app
    restart: always
    entrypoint: ["bash", "./entrypoint.sh"]
